//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `ServiceApi.plist`.
    static let serviceApiPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "ServiceApi", pathExtension: "plist")
    
    /// `bundle.url(forResource: "ServiceApi", withExtension: "plist")`
    static func serviceApiPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.serviceApiPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 0 images.
  struct image {
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 2 nibs.
  struct nib {
    /// Nib `DBDetailViewCell`.
    static let dbDetailViewCell = _R.nib._DBDetailViewCell()
    /// Nib `DBFeedViewCell`.
    static let dbFeedViewCell = _R.nib._DBFeedViewCell()
    
    /// `UINib(name: "DBDetailViewCell", in: bundle)`
    static func dbDetailViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.dbDetailViewCell)
    }
    
    /// `UINib(name: "DBFeedViewCell", in: bundle)`
    static func dbFeedViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.dbFeedViewCell)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 2 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `DBDetailViewCell`.
    static let dbDetailViewCell: Rswift.ReuseIdentifier<DBDetailViewCell> = Rswift.ReuseIdentifier(identifier: "DBDetailViewCell")
    /// Reuse identifier `DBFeedViewCellIdentifier`.
    static let dbFeedViewCellIdentifier: Rswift.ReuseIdentifier<DBFeedViewCell> = Rswift.ReuseIdentifier(identifier: "DBFeedViewCellIdentifier")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    /// This `R.string.details` struct is generated, and contains static references to 1 localization keys.
    struct details {
      /// Value: Details
      static let detailTitle = Rswift.StringResource(key: "detailTitle", tableName: "Details", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: Details
      static func detailTitle(_: Void = ()) -> String {
        return NSLocalizedString("detailTitle", tableName: "Details", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    /// This `R.string.feed` struct is generated, and contains static references to 1 localization keys.
    struct feed {
      /// Value: Movies
      static let moviesTitle = Rswift.StringResource(key: "moviesTitle", tableName: "Feed", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: Movies
      static func moviesTitle(_: Void = ()) -> String {
        return NSLocalizedString("moviesTitle", tableName: "Feed", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    struct _DBDetailViewCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = DBDetailViewCell
      
      let bundle = R.hostingBundle
      let identifier = "DBDetailViewCell"
      let name = "DBDetailViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> DBDetailViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? DBDetailViewCell
      }
      
      fileprivate init() {}
    }
    
    struct _DBFeedViewCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = DBFeedViewCell
      
      let bundle = R.hostingBundle
      let identifier = "DBFeedViewCellIdentifier"
      let name = "DBFeedViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> DBFeedViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? DBFeedViewCell
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let detailViewController = StoryboardViewControllerResource<DBDetailViewController>(identifier: "detailViewController")
      let name = "Main"
      
      func detailViewController(_: Void = ()) -> DBDetailViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: detailViewController)
      }
      
      static func validate() throws {
        if _R.storyboard.main().detailViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'detailViewController' could not be loaded from storyboard 'Main' as 'DBDetailViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
