source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

def testing_pods
    
end

target 'Movies' do
    
    pod 'Kingfisher', '~> 4.0'
    pod 'SnapKit', '~> 4.0.0'
    pod 'Moya', '~> 11.0'
    pod 'NVActivityIndicatorView'
    pod 'Alertift', '~> 3.0'
    
    target 'MoviesTests' do
        inherit! :search_paths
        pod 'Quick'
        pod 'Nimble'
        pod 'OHHTTPStubs/Swift'
        testing_pods
    end
    
end
